// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: api/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Control_Enroll_FullMethodName = "/veilink.control.v1.Control/Enroll"
	Control_Pull_FullMethodName   = "/veilink.control.v1.Control/Pull"
	Control_Events_FullMethodName = "/veilink.control.v1.Control/Events"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// All envelopes are genuine protobuf Struct, never a custom JSON codec.
// Enroll request: node_id:string, token:string. Response: credential:string.
// Pull request: node_id:string, credential:string. Response: model.Snapshot
// field names (revision, node, nodes, bindings, mappings). UUID exists only here.
// Events client: node_id:string, credential:string, applied_revision:number,
// error:string (presence indicates failure; content never persisted).
// Events server: revision:number. Client sends heartbeat at least every 15s,
// pulls on every new revision and retries failed applications of same revision.
// Numeric revisions are limited to protobuf Struct exact integers (<2^53).
type ControlClient interface {
	Enroll(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	Pull(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	Events(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[structpb.Struct, structpb.Struct], error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Enroll(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, Control_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Pull(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, Control_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Events(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[structpb.Struct, structpb.Struct], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[0], Control_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[structpb.Struct, structpb.Struct]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_EventsClient = grpc.BidiStreamingClient[structpb.Struct, structpb.Struct]

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
//
// All envelopes are genuine protobuf Struct, never a custom JSON codec.
// Enroll request: node_id:string, token:string. Response: credential:string.
// Pull request: node_id:string, credential:string. Response: model.Snapshot
// field names (revision, node, nodes, bindings, mappings). UUID exists only here.
// Events client: node_id:string, credential:string, applied_revision:number,
// error:string (presence indicates failure; content never persisted).
// Events server: revision:number. Client sends heartbeat at least every 15s,
// pulls on every new revision and retries failed applications of same revision.
// Numeric revisions are limited to protobuf Struct exact integers (<2^53).
type ControlServer interface {
	Enroll(context.Context, *structpb.Struct) (*structpb.Struct, error)
	Pull(context.Context, *structpb.Struct) (*structpb.Struct, error)
	Events(grpc.BidiStreamingServer[structpb.Struct, structpb.Struct]) error
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) Enroll(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedControlServer) Pull(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedControlServer) Events(grpc.BidiStreamingServer[structpb.Struct, structpb.Struct]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Enroll(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Pull(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServer).Events(&grpc.GenericServerStream[structpb.Struct, structpb.Struct]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_EventsServer = grpc.BidiStreamingServer[structpb.Struct, structpb.Struct]

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veilink.control.v1.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _Control_Enroll_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _Control_Pull_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _Control_Events_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/control/v1/control.proto",
}
