// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: api/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_control_v1_control_proto protoreflect.FileDescriptor

const file_api_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1capi/control/v1/control.proto\x12\x12veilink.control.v1\x1a\x1cgoogle/protobuf/struct.proto2\xbf\x01\n" +
	"\aControl\x12:\n" +
	"\x06Enroll\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct\x128\n" +
	"\x04Pull\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct\x12>\n" +
	"\x06Events\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct(\x010\x01B\"Z veilink/api/control/v1;controlv1b\x06proto3"

var file_api_control_v1_control_proto_goTypes = []any{
	(*structpb.Struct)(nil), // 0: google.protobuf.Struct
}
var file_api_control_v1_control_proto_depIdxs = []int32{
	0, // 0: veilink.control.v1.Control.Enroll:input_type -> google.protobuf.Struct
	0, // 1: veilink.control.v1.Control.Pull:input_type -> google.protobuf.Struct
	0, // 2: veilink.control.v1.Control.Events:input_type -> google.protobuf.Struct
	0, // 3: veilink.control.v1.Control.Enroll:output_type -> google.protobuf.Struct
	0, // 4: veilink.control.v1.Control.Pull:output_type -> google.protobuf.Struct
	0, // 5: veilink.control.v1.Control.Events:output_type -> google.protobuf.Struct
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_control_v1_control_proto_init() }
func file_api_control_v1_control_proto_init() {
	if File_api_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_v1_control_proto_goTypes,
		DependencyIndexes: file_api_control_v1_control_proto_depIdxs,
	}.Build()
	File_api_control_v1_control_proto = out.File
	file_api_control_v1_control_proto_goTypes = nil
	file_api_control_v1_control_proto_depIdxs = nil
}
